default_stages: [commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: check-case-conflict

-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      -  id: isort
         args: ['--profile', 'black', '--filter-files']

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: ['--ignore-django-orm-queries-complexity']
        additional_dependencies: [
            flake8-annotations-complexity,
            flake8-bandit,
            flake8-blind-except,
            flake8-breakpoint,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-debugger,
            flake8-django,
            flake8-eradicate,
            flake8-expression-complexity,
            flake8-logging-format,
            flake8-pep3101,
            flake8-plugin-utils,
            flake8-polyfill,
            flake8-print,
            flake8-quotes,
            flake8-return,
            flake8-string-format,
            flake8-trailing-commas
        ]
